### ISSUE TITLE
[$50] Cancelled challenge not accessible

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1019] opened 2020-12-28 23:40 UTC
### Expected behavior
I would expect cancelled challenges (due to no submission, failed review, client request, etc...) to be accessible somewhere in Work Manager, especially if we need to repost something.  

### Actual behavior
As far as I can tell, cancelled challenges disappear from work manager and aren't accessible on `Active`, `New`, `Draft`, or `Completed` tabs for a project.

### Steps to reproduce the problem
- Run a challenge from WM
- Cancel the challenge
- Challenge is no long able to be found in WM

**Comment by vikasrohit** [comment] 2021-01-05 12:17
@maxceem lets add a new tab called `Cancelled` which would list all cancelled challenges.

**Comment by maxceem** [comment] 2021-01-06 10:23
@vikasrohit I'm trying to reproduce this issue, but have some difficulties with canceling challenges.

I've canceled 3 challenges using OnlineReview:

![image](https://user-images.githubusercontent.com/146016/103757731-d998b400-5019-11eb-9999-97d9bb369cb9.png)

I waited around 20 minutes, but they are still "draft" in V5, so it looks like status wasn't synced back from OR to v5. See all these challenges in OR are cancelled:
https://software.topcoder-dev.com/review/actions/ViewProjectDetails?pid=30057916
https://software.topcoder-dev.com/review/actions/ViewProjectDetails?pid=30057845
https://software.topcoder-dev.com/review/actions/ViewProjectDetails?pid=30057849

**Comment by vikasrohit** [comment] 2021-01-06 10:29
You may be right @maxceem. I think forward sync only pulls active and completed challenges back to V5. We need @rootelement 's help here. @rootelement can you please confirm if the forward sync brings back the cancelled challenges to v5 or not?

**Comment by rootelement** [comment] 2021-01-21 20:29
The v4 -> v5 sync:
1. Gets the challenges in legacy with a status of Active
2. Gets the challenges in v5 with a status of Active
3. Aggregates the legacy IDs and deduplicates them
4. Performs the sync

If you change a challenge status from anything _but_ Active (ie Draft) to Canceled, it will not sync forward from legacy. I'm not sure how to fix this. It would be better if we had the means to cancel the challenge from WM, so it'd be canceled from the community app side right away then propagate back to legacy.

**Comment by vikasrohit** [comment] 2021-01-22 11:36
Thanks for the detailed response @rootelement. Would it just take a simple PATCH call to v5 challenge api to cancel the challenge?

**Comment by rootelement** [comment] 2021-02-24 00:19
Sorry I didn't see this. Yes, patching as canceled would work. We could also add it in WM as it currently is in OR, but I don't know if we need business rules around it (who can do it, when can you, when can't you)

**Comment by acshields** [comment] 2021-03-29 16:44
@vikasrohit @rootelement - Tony was asking whether this issue could be tackled during our next cool down period. Do you think that this could be accomplished then, or does this issue require a project pitch?

**Comment by vikasrohit** [comment] 2021-03-30 11:18
@acshields we can cancel a `Draft` challenge from WM but if a challenge is cancelled in legacy apps it won't be synced back to WM. @rootelement please correct me if I am wrong here.

**Comment by rootelement** [comment] 2021-03-30 14:21
Right now a challenge has to be "Active" in either v4 or v5 to be synced. If a challenge is Draft in legacy and Canceled on V5, it won't sync at all.

**Comment by acshields** [comment] 2021-03-30 15:39
@rootelement - IYO, is the juice worth the squeeze to do enable this sync so canceled challenges can be be seen in WM, or will it open the door for complications?

**Comment by ajefts** [comment] 2021-03-30 16:03
The important use case here is to cover challenges that were active and then finished with a canceled status.  If it goes from Draft directly to Canceled I don't think we really care.  However, if it goes from Active to "Canceled - Failed Review" then we need to see it since it actually happened, impacts costs/timelines/fulfillment/etc.

**Comment by acshields** [comment] 2021-03-30 16:56
@ajefts - fair call out. @rootelement - I am still curious to hear if there are any repercussions we need to think through. I am thinking back to when we had the very long sync timing, which was partially tied to when we were syncing to legacy in draft state. I know that was addressed, but just curious if we would run into any complications along those lines.

**Comment by vikasrohit** [comment] 2021-04-01 05:10
From @rootelement's explanation what I understand is that, @ajefts's use case is going to be working because challenge is moving from Active to Cancelled, and I think it should already be true. @ajefts do you have any recent example of such challenge on production?
And the other use case where the challenge was moved directly to Cancelled status, I think once we implement cancel button in WM, we should be good with it. Such challenges would be listed in WM (we have to add a Cancel status tab to view them) and they won't be visible in any legacy app.

**Comment by rootelement** [comment] 2021-04-01 05:15
Tony found a "way around" by direct-entering the URL into connect, editing the challenge, saving as draft and then activating again, but... not sure about that flow. This may be a good use case for admin.topcoder.com instead of working it into WM

**Comment by vikasrohit** [comment] 2021-05-05 16:01
@rootelement @ajefts @acshields do we need feature to cancel the challenge from WM?

**Comment by ajefts** [comment] 2021-06-10 15:37
@rootelement @vikasrohit Sorry, trying to catch up on this one.  Is it not desired to simply sync cancelled challenges from legacy to v5?

**Comment by vikasrohit** [comment] 2021-06-28 13:48
Moving to next milestone @ajefts, we didn't get time to wrap this one in this milestone. We need to add `Cancelled` tab to the list of challenges but we need to check if the API supports filtering challenges based on multiple challenges because we have many variations of `Cancelled` status.

**Comment by yoution** [comment] 2021-07-01 07:16
@phead198708 please assign to me

**Comment by yoution** [comment] 2021-07-02 02:26
@phead198708 please review https://github.com/topcoder-platform/work-manager/pull/1212

**Comment by coderhacker** [comment] 2021-07-09 12:41
Dev Passed: 

https://user-images.githubusercontent.com/62358241/125079242-028d2500-e0e1-11eb-9af0-4108cf5d1311.mp4

**Comment by yoution** [comment] 2021-07-10 05:18
@vikasrohit @phead198708 please add payment

**Comment by coderhacker** [comment] 2021-07-12 15:09
This is passed on to production 

https://user-images.githubusercontent.com/62358241/125311678-340c2780-e351-11eb-953f-db9953657249.mp4

**Closed by coderhacker** 2021-07-12 15:09 UTC
Labels: Dev Environment, Prod Environment, QA Pass in Dev, QA Pass in Prod, Ready for Prod QA
