### ISSUE TITLE
Getting 'Member with userId: 23278999 is not registered on the challenge' when user tries to close a Task

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#800] opened 2020-09-10 13:06 UTC
As you mentioned on the [comment ](https://github.com/topcoder-platform/challenge-engine-ui/issues/693#issuecomment-687082375) I am getting `Member with userId: 23278999 is not registered on the challenge` 

![image](https://user-images.githubusercontent.com/42398485/92652643-da5f4a80-f2b2-11ea-8863-f23e08b01a7d.png)

[2.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5197866/2.zip)

> Though at the moment when I'm trying to close the task with the assigned member who is added as a winner there is an error. I guess setting task.memberId doesn't add the user to the challenge, because when I send the same request but without winners array, it works, and the challenge is marked as completed:

> So until the server code is fixed, when we click the Confirm button we would always get a server error.

**Comment by vikasrohit** [comment] 2020-09-16 12:55
Thanks @codejamtc. This issue is only for tracking purposes in Work Manager, original work needed is being done under https://github.com/topcoder-platform/legacy-challenge-resource-processor/issues/12

**Comment by codejamtc** [comment] 2020-09-16 18:14
This is happening in prod also

![image](https://user-images.githubusercontent.com/42398485/93376002-958d6380-f81e-11ea-9e95-0b825c2c1c33.png)


[2.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5234099/2.zip)

**Comment by vikasrohit** [comment] 2020-09-17 05:33
This seems to be a slightly a different case as you are trying to assign the task to an already member of the team i.e. a user who is already in different role (copilot in this case). Original error reported in the issue is about the assigned user is not part of the challenge yet. Root cause of both the issues is business logic placed in v4 legacy api, so they might get fixed with the same fix but there is still a possibility that this new case might need more changes in Work Manager. So, I would like to create a separate issue for this for clear tracking and link the two issues together.

**Comment by vikasrohit** [comment] 2020-09-25 11:54
@lakshmiathreya @codejamtc marking ready for QA because the underlying issue with legacy-challenge-resource-processor is supposed to be fixed now.

Note: I am seeing couple of issues though:

**Comment by drasticdpk** [comment] 2020-09-28 08:41
Unable to replicate the scenario, will test once fixed below issue.
https://github.com/topcoder-platform/challenge-engine-ui/issues/822

**Comment by vikasrohit** [comment] 2020-09-28 09:04
@drasticdpk please test the fix with non copilot account, #822 is only valid for copilots. Even, with copilot account you may try assigning task to yourself, it that works.

**Comment by drasticdpk** [comment] 2020-09-28 15:00
@vikasrohit , I have created the challenge (type task) and assign to user (any).
Unfortunately that challenge is not listed either copilot or user.
Reference : 
![image](https://user-images.githubusercontent.com/25297859/94449021-54586480-01cb-11eb-8ea5-cf0675376039.png)

**Comment by vikasrohit** [comment] 2020-09-28 17:29
Yes, that is why I was saying that please use a non admin account for testing this specific issue as the issue is not role specific. Anyway, I think now https://github.com/topcoder-platform/challenge-engine-ui/issues/822 is fixed, so you should be able to test it with copilot account as well.

**Comment by drasticdpk** [comment] 2020-09-29 02:17
Verified on dev mode
![image](https://user-images.githubusercontent.com/25297859/94505077-03c42400-022a-11eb-92c8-b5068d132086.png)

**Comment by sandhiyakavi** [comment] 2020-11-20 07:35
@vikasrohit Still getting "Member with userId: 40911557 is not registered on the challenge" .

Challenge used: https://challenges.topcoder.com/projects/24943/challenges/cf8fb1fe-2ff1-4f6f-9afe-df7f42faac97

![image](https://user-images.githubusercontent.com/55895538/99772575-5f39d080-2b4e-11eb-9b89-f61c185318c5.png)

**Comment by vikasrohit** [comment] 2020-11-23 06:54
@sandhiyakavi can you please try it couple of times more? It seems there is some time required for the resource to be synced back to legacy. And if because of some error or timing issue, legacy is not synced, it removes the resource from v5 as well. But this scenario should happen rarely not every time. If we are seeing this behavior every time, we might need to revisit the logic in resource legacy sync.

fyi @rootelement @ThomasKranitsas @mtwomey @acshields

**Comment by sandhiyakavi** [comment] 2020-11-23 08:47
@vikasrohit Tried creating few tasks. This error happens for the below scenario.

Steps to reproduce:
1. Create a task without assigning a member
2. Click Save Draft.
3. Click Launch as Active.
4. Wait for 3 to 4 mins for the challenge to be created in legacy.
5. Click Edit button and assign a member.
6. Click Close Task button.
7. Click confirm in the popup.
8. Check if error appears.

Note: This error doesn't happen if we save (the task start date should be present date) the assigned member before clicking Close Task button

[issue_retest.zip](https://github.com/topcoder-platform/work-manager/files/5581761/issue_retest.zip)

**Comment by vikasrohit** [comment] 2020-11-24 17:45
Good catch @sandhiyakavi it seems it more or less UI flow issue. `Close Task` button does not save the changes in the form. So, we can mark it disabled when the form is dirty. Can you please create a separate issue for it? And if apart from it, every thing is working fine, we can close this one.

**Comment by sandhiyakavi** [comment] 2020-11-25 04:14
The issue https://github.com/topcoder-platform/work-manager/issues/800#issuecomment-732016812 is tracked separately in https://github.com/topcoder-platform/work-manager/issues/913

**Closed by sandhiyakavi** 2020-11-25 04:14 UTC
Labels: Functional, P0, Prod Environment, QA Fail in Prod, QA Pass in Dev

**Comment by lakshmiathreya** [comment] 2020-12-07 17:22
@sandhiyakavi pls update the Prod QA status for this Issue. cc @drasticdpk
