### ISSUE TITLE
'Maximum Number of Submissions' is not displayed correctly on the draft challenge page

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#783] opened 2020-09-01 19:49 UTC
![image](https://user-images.githubusercontent.com/42398485/91899002-2c282500-ec62-11ea-8c05-3f163615732c.png)

![image](https://user-images.githubusercontent.com/42398485/91899079-4235e580-ec62-11ea-8697-0e5d452961ff.png)

### Steps to reproduce the problem

1. Open https://challenges.topcoder-dev.com/ and login as Admin
2. Select a project from the list 'Test v5 {codejam} - 0001'
3. Click 'Launch New'
4. Select Work Type=Design; Format=Challenge; Name=Test
5. Click 'Continue Set-Up'
6. Set Maximum Number of Submissions : 50
7. Click Save Draft
8. Click Back
9. Click 'View Challenge' - https://www.topcoder-dev.com/challenges/900c4bda-d798-4221-b66b-86c116ba932c

### Actual behavior
- 'Maximum Number of Submissions' is not displayed correctly on the draft challenge page

### Expected behavior
- Should display the correct 'Maximum Number of Submissions' 

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Admin
**- Account used:**  `TonyJ`

**Comment by vikasrohit** [comment] 2020-09-02 08:07
Good catch @codejamtc 

@rootelement I think it is issue with legacy processor, do you want us to create separate issue in its repo?

**Comment by rootelement** [comment] 2020-09-21 16:38
This is the code used in the migration script:
```
const metadata = []
  if (challengeListing.fileTypes && challengeListing.fileTypes.length > 0) {
    const fileTypes = _.map(challengeListing.fileTypes, fileType => fileType.description)
    // console.log(fileTypes)
    metadata.push({ name: 'fileTypes', value: JSON.stringify(fileTypes) })
  }

  const metadataList = ['allowStockArt', 'drPoints', 'submissionViewable', 'submissionLimit', 'codeRepo', 'environment']
  const allMetadata = _.map(metadataList, item => {
    if (challengeListing[item]) return { name: item, value: _.toString(challengeListing[item]) }
  })
  metadata.push(..._.compact(allMetadata))
```

So the valid values are:
 - fileTypes
 - allowStockArt
 - drPoints
 - submissionViewable
 - submissionLimit
 - codeRepo
 - environment

**Comment by maxceem** [comment] 2020-09-22 10:31
@codejamtc I cannot reproduce this issue. I guess it has been fixed.

**Comment by vikasrohit** [comment] 2020-09-22 11:12
@codejamtc @drasticdpk marked it as ready for QA as it is not reproducible as of now.

**Comment by codejamtc** [comment] 2020-09-22 12:38
@maxceem @vikasrohit Yes, fixed in dev

**Comment by sandhiyakavi** [comment] 2020-11-19 11:40
@vikasrohit The "Maximum number of Submissions" is not displayed correctly in Prod. Displaying as 'unlimited' by default.

Challenge : https://www.topcoder.com/challenges/bfd8aff1-c5e2-4e3c-b54c-b15b750e3eb8
Challenge in WM: https://challenges.topcoder.com/projects/24887/challenges/bfd8aff1-c5e2-4e3c-b54c-b15b750e3eb8

![image](https://user-images.githubusercontent.com/55895538/99661438-2c88cd00-2aa7-11eb-9ccf-cabfcc3a84ec.png)
![image](https://user-images.githubusercontent.com/55895538/99661492-3f030680-2aa7-11eb-8401-427a059d91c8.png)

**Comment by vikasrohit** [comment] 2020-11-23 05:41
@rootelement @ThomasKranitsas do you guys have any idea why it is working in dev but not on production.

**Comment by lakshmiathreya** [comment] 2020-12-07 14:53
Maximum Number of Submissions not synced in Prod.

**Comment by vikasrohit** [comment] 2021-01-05 10:27
@rootelement I guess it fixed in one of the releases in later half of the last month, right? or do you think something is still pending to resolve it?

**Comment by drasticdpk** [comment] 2021-01-19 10:36
still having same issue
![image](https://user-images.githubusercontent.com/25297859/105022875-5a23cf80-5a72-11eb-97db-142dc78924d0.png)
https://challenges.topcoder.com/projects/24943/challenges/670990d0-fe14-4ce5-9671-ddfbc852f654/view

**Comment by maxceem** [comment] 2021-01-19 10:43
@rootelement could you please, help us here. What is the expected format of data for `submissionLimit`? Here is how we store it in WM:
```js
{ 
   metadata: [
      {
          "name":"submissionLimit",
          "value":"{\"count\":\"4\",\"limit\":\"true\",\"unlimited\":\"false\"}"
      }
  ]
}    
```

![image](https://user-images.githubusercontent.com/146016/105023313-7a906180-5a53-11eb-8eb7-830a091decbc.png)

**Comment by ThomasKranitsas** [comment] 2021-01-19 10:47
@maxceem FYI https://github.com/topcoder-platform/legacy-challenge-processor/blob/develop/src/services/ProcessorService.js#L556

**Comment by maxceem** [comment] 2021-01-19 10:51
Thank you @ThomasKranitsas.

@drasticdpk as per code, shared by Thomas, Work Manager set maximum submissions correctly. So this looks like an issue in the Communiy App, it doesn't display it correctly.

**Comment by vikasrohit** [comment] 2021-01-20 08:40
@acshields can you please get it carried over to Community team? We can close it after that is resolved there.

**Comment by vikasrohit** [comment] 2021-01-20 13:28
I am moving it out from the milestone for now.

**Comment by acshields** [comment] 2021-01-20 16:57
@vikasrohit - yes, I will pass this onto Oanh.

**Closed by acshields** 2021-01-20 16:57 UTC
Labels: Functional, P4, QA Fail in Prod, QA Pass in Dev, legacy-sync
