### ISSUE TITLE
No way to close a challenge of type TASK

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/work-manager#693] opened 2020-06-15 17:04 UTC
There should be a way to manually close a challenge of type `TASK`

**Comment by vikasrohit** [comment] 2020-06-17 05:31
Do we have option to close any other type of challenge manually as of now?

@acshields fyi, moving it to `V2:MVP` for now. Please prioritize as per needs. I think this would be already in your list of features after pilot release.

**Comment by ThomasKranitsas** [comment] 2020-06-17 09:29
Well, the API does support marking phases as open/not open (using the `isOpen` boolean) and also allows setting the `challenge.status` property. (eg `Draft`, `Active`, `Completed` etc).

Even the current app (OR) allows closing any type of challenge manually (eg you can cancel a challenge with status `Canceled - Client Request` etc)

I'm not entirely sure how this is supposed to work on the v5 ecosystem.

cc @rootelement

**Comment by vikasrohit** [comment] 2020-06-17 13:57
Agreed. The reason, I am putting it in after first release is that it is not our primary use case for the first release as user can close the task from legacy for the first few releases.

**Comment by rootelement** [comment] 2020-08-13 16:08
After speaking with @ThomasKranitsas in slack, I see a couple things that have to happen.

1. If the user is creating a task, there should be a field on the Creation/Edit page to Add an "Assignee" which searches all active members.
2. In the list view, there should be two options added:
   - Assign User - This button should be active unless the task is closed
   - Close Task - This button should be disabled until there's an assignee.
3. Also in the list view, if it's a type task and there's a an assignee, the member's handle should show up.

As far as the API fo We only need to:
- assign a member
- Mark status as completed
- Set the winner in the winners array
- PUT the challenge

Lastly, and out of the scope of this issue, in terms of React, I think the list view needs to be refactored a little bit to have a Component for each challenge type in that row. That will allow us to change what information is displayed based on Type. F2F could have pending reviews, Task has the assignee stuff, Challenge could have more info about registrants and appeals and stuff. But this can be broken out into another issue.

**Comment by maxceem** [comment] 2020-08-19 08:33
1. @vikasrohit as suggested by James we should show `Close Task` button on the list. I would also suggest adding such a button on the challenge `edit` page, as a third button here:

![image](https://user-images.githubusercontent.com/146016/90611082-f1a89c00-e20e-11ea-8ef9-f27fa2f0f6a3.png)

2. Should we show a confirmation modal when we click `Close Task` button as this action cannot be undone, and money would be paid after this action. Such a modal can show the essential information to confirm:
    - task name
    - task prize
    - assigned member
    - also could show copilot handle and copilot fee to confirm too

3. > Also in the list view, if it's a type task and there's a an assignee, the member's handle should show up.

    If a member has been already assigned, should we still show the `Assign User` button to allow changing the assigned member from the challenge list view?

**Comment by vikasrohit** [comment] 2020-08-19 13:22
Good questions @maxceem 

1. Yes, we need a button at edit page as well. However, the current display and cadence of the buttons is not optimal yet. We are thinking of improving it because it is confusing as of now. We don't have a way to update a challenge without moving it to Draft status which causes too much work for legacy processors and increases the possibility of inconsistencies. So, I would suggest showing a Close Task button (not launch and close) only when the challenge is in active status.

2. That would be good


3. yes, we need to show Assign User button still to allow changing the assigned member until the challenge is completed. However, I would suggest not do changes in the list view as of now, we will handle that separately.

**Comment by maxceem** [comment] 2020-08-19 13:26
@vikasrohit 
> I would suggest not do changes in the list view as of now, we will handle that separately.

Do you mean not doing refactoring of the list view as was mentioned by James, or do you mean that we shouldn't even add `Assign User` button the list and only add it to the `edit` page for now?

**Comment by vikasrohit** [comment] 2020-08-20 10:02
Yes, both. Lets not touch the list view for now. We would have the functionality in edit view anyway. I don't want to spend time in adding features to list view before the real designs come.

**Comment by maxceem** [comment] 2020-08-20 10:32
@vikasrohit done via https://github.com/topcoder-platform/challenge-engine-ui/pull/762

**Comment by vikasrohit** [comment] 2020-09-04 11:09
@drasticdpk @codejamtc marked it ready for review, however, there are certain known facts and issues with this fetaure. @maxceem could you please describe and link the api/legacy processor issues which are preventing this feature to work successfully.

**Comment by maxceem** [comment] 2020-09-04 11:15
- Button to close the task added to the edit page, but not the list, as confirmed by Vikas https://github.com/topcoder-platform/challenge-engine-ui/issues/693#issuecomment-677504044

   - `Close Task` button is only showed **after** the challenge is activated as clarified by Vikas https://github.com/topcoder-platform/challenge-engine-ui/issues/693#issuecomment-676348881

   ![image](https://user-images.githubusercontent.com/146016/90759136-b1b5e780-e2e8-11ea-95d8-27671303ea86.png)

- As not all the fields which are needed to close a task are required in the form, I've added an error message which asks user to fill all the fields for closing task:

   ![image](https://user-images.githubusercontent.com/146016/90759401-09545300-e2e9-11ea-837d-b06257a402b5.png)

- If all required info is there and user clicks `Close Task` button, there is a confirmation dialog:

   ![image](https://user-images.githubusercontent.com/146016/90759092-a06cdb00-e2e8-11ea-9022-fea0e9899572.png)

- If user clicks `Confirm` form is being processed and a standard successful message is showing:

   ![image](https://user-images.githubusercontent.com/146016/90759638-60f2be80-e2e9-11ea-8816-6ab76804a8d9.png)
   
  Though at the moment when I'm trying to close the task with the assigned member who is added as a winner there is an error. I guess setting `task.memberId` doesn't add the user to the challenge, because when I send the same request but without `winners` array it works, and the challenge is marked as completed:
   
   ![image](https://user-images.githubusercontent.com/146016/90762634-060f9600-e2ee-11ea-8d90-5a9bc1fbce13.png)

So until server code is fixed, when we click `Confirm` button we would always get server error.

**Comment by codejamtc** [comment] 2020-09-04 17:13
URL: https://challenges.topcoder-dev.com/projects/16604/challenges/c0db7bbb-9437-49ad-9c8e-ce513e187517/edit

- `Close Task` button is displayed on the edit page only  🆗 
![image](https://user-images.githubusercontent.com/42398485/92264907-98926680-eea4-11ea-80e8-792367dce6d7.png)

2. As not all the fields which are needed to close a task are required in the form, I've added an error message which asks user to fill all the fields for closing task:

- I can't see the popup, instead `Please fix the errors before saving` displayed

![image](https://user-images.githubusercontent.com/42398485/92268183-8d8d0580-eea7-11ea-8e22-3728058fb3ce.png)

3. If all required info is there and user clicks Close Task button, there is a confirmation dialog:

- I can't see the popup, instead `Please fix the errors before saving` displayed

[17.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5176116/17.zip)


@maxceem Please check this again and confirm

**Comment by maxceem** [comment] 2020-09-07 07:27
@codejamtc 2 and 3 are caused by another issue https://github.com/topcoder-platform/challenge-engine-ui/issues/776. It's not fixed yet, though it shouldn't happen for new challenges, only for old challenges.

Could please create a new challenge (Task) to verify this ticket.

**Comment by codejamtc** [comment] 2020-09-07 16:46
@maxceem Please check the video for the new task
[1.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5184074/1.zip)

**Comment by vikasrohit** [comment] 2020-09-08 12:04
@maxceem Did you get chance to look at what is causing the symptoms of #776 for a new task?

**Comment by maxceem** [comment] 2020-09-08 12:12
> @maxceem Did you get chance to look at what is causing the symptoms of #776 for a new task?

I couldn't reproduce it yet. As per @codejamtc video from comment https://github.com/topcoder-platform/challenge-engine-ui/issues/693#issuecomment-688432395 there are many other issues, including #776 but the way it's reproduced there is very complicated. I would give it a try one more time.

**Comment by maxceem** [comment] 2020-09-08 14:43
@vikasrohit I've tried to reproduce #776 playing with `internal` reviewer but still cannot reproduce it again even once.

**Comment by maxceem** [comment] 2020-09-08 14:51
@codejamtc regarding the issue you have during `launching` the challenge. It looks like it happens if we lunch the challenge too fast after creating.

![image](https://user-images.githubusercontent.com/146016/92492040-965d3e80-f1fb-11ea-997c-611781cd7de5.png)

Could you please, try to create a new challenge, but wait 5-10 minutes before clicking `launch as active`. And then try to validate this issue.

**Comment by codejamtc** [comment] 2020-09-09 20:41
@maxceem It's working

As you mentioned on the comment I am getting `Member with userId: 23278999 is not registered on the challenge` 

![image](https://user-images.githubusercontent.com/42398485/92652643-da5f4a80-f2b2-11ea-8863-f23e08b01a7d.png)

[2.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5197866/2.zip)

**Comment by vikasrohit** [comment] 2020-09-10 05:51
Good idea @codejamtc, I think we can close this one and log a new issue for the issue we are facing from server side. That would clear the picture that UI features are done by something is pending from server side.

**Comment by codejamtc** [comment] 2020-09-10 13:07
server-side issue is tracked by https://github.com/topcoder-platform/challenge-engine-ui/issues/800

**Comment by sandhiyakavi** [comment] 2020-11-20 06:30
@vikasrohit The pop up message displayed if the Assigned member, copilot name and fee not entered ,is mentioning to assign task member alone .

![image](https://user-images.githubusercontent.com/55895538/99765818-36f8a480-2b43-11eb-9a03-a25740cc6a47.png)

After assigning member, copilot name and copilot fee, only Assigned member with their pay is displayed,
![image](https://user-images.githubusercontent.com/55895538/99766373-4e845d00-2b44-11eb-9dc8-ce081875f4d0.png)

**Comment by vikasrohit** [comment] 2020-11-20 07:09
Yes that is as per requirements #896

**Closed** 2020-11-20 07:17 UTC
Labels: P1, QA Pass in Dev, QA Pass in Prod
