### ISSUE TITLE
[$100] Work Manager: Add view of submissions to WM

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#1169] opened 2021-06-10 05:15 UTC
When viewing a challenge in WM I should be able to see a list of the submissions.

Mimic the submission list on the challenge page:

![image](https://user-images.githubusercontent.com/2417632/121468733-ec545200-c9d8-11eb-9245-03f96e02b3a2.png)

When a score is available, display it.

Provide a link to the submission review app.

**Comment by phead198708** [comment] 2021-06-15 17:50
for submissions we have separate API https://github.com/topcoder-platform/submissions-api/blob/develop/docs/swagger.yaml#L31

**Comment by phead198708** [comment] 2021-06-15 17:52
Challenge https://www.topcoder.com/challenges/6c1e79b5-37d4-4012-9c83-0aee9d8fb8eb has been created for this ticket.<br/><br/>```This is an automated message for phead via Topcoder X```

**Comment by phead198708** [comment] 2021-06-15 17:53
@bug_bash_helper assign

**Comment by phead198708** [comment] 2021-06-15 17:54
@bug-bash-helper assign

**Comment by yoution** [comment] 2021-06-18 02:52
@bug-bash-helper assign

**Comment by yoution** [comment] 2021-06-18 02:52
@phead198708  please assign to me

**Comment by yoution** [comment] 2021-06-18 03:28
@bug-bash-helper assign

**Comment by yoution** [comment] 2021-06-18 03:31
@bug-bash-helper assign

**Comment by phead198708** [comment] 2021-06-18 03:31
Challenge https://www.topcoder.com/challenges/6c1e79b5-37d4-4012-9c83-0aee9d8fb8eb has been assigned to yoution.<br/><br/>```This is an automated message for phead via Topcoder X```

**Comment by phead198708** [comment] 2021-06-18 04:23
Hi, @yoution 

Pls update the style of tab section also. move the tab to the middle, add some padding to the top.

**Comment by yoution** [comment] 2021-06-18 10:14
@bug-bash-helper https://github.com/topcoder-platform/work-manager/pull/1186 is ready for review

**Comment by phead198708** [comment] 2021-06-18 12:25
Hi, @yoution 

Some feedback:

1. the position of table is not correct. Keep it same with registration.
![image](https://user-images.githubusercontent.com/85940583/122560455-355c7400-d073-11eb-89c0-7a257c9f4dfd.png)

**Comment by yoution** [comment] 2021-06-19 03:22
@phead198708 have pushed, please review

**Comment by coderhacker** [comment] 2021-06-25 09:45
It's failing due to this regression issue https://github.com/topcoder-platform/work-manager/issues/1198

**Comment by drasticdpk** [comment] 2021-06-25 12:00
With reference to discussion over slack, we have verified this req with past challenge. 
https://challenges.topcoder-dev.com/projects/17090/challenges/89ae709a-cb5f-434f-a8cb-2efa05ed3f42/view 
We can open new ticket for anything, overall task is completed.   cc @coderhacker @lakshmiathreya @vikasrohit 
**Reference** 
![image](https://user-images.githubusercontent.com/25297859/123421817-14e56a00-d5dd-11eb-9273-cbb87a25b13c.png)

**Comment by coderhacker** [comment] 2021-06-28 13:45
This is passed on to production 

https://user-images.githubusercontent.com/62358241/123646761-203ace80-d845-11eb-935a-25fbc87c3ecf.mp4

**Comment by phead198708** [comment] 2021-06-28 13:45
Payment task has been updated: https://www.topcoder.com/challenges/6c1e79b5-37d4-4012-9c83-0aee9d8fb8eb
*Payments Complete*
Winner: yoution
Copilot: phead
Challenge `6c1e79b5-37d4-4012-9c83-0aee9d8fb8eb` has been paid and closed.<br/><br/>```This is an automated message for phead via Topcoder X```

**Closed by coderhacker** 2021-06-28 13:45 UTC
Labels: CF, Dev Environment, Feedback, P2, QA Pass in Dev, QA Pass in Prod, tcx_Assigned, tcx_FixAccepted
