### ISSUE TITLE
The buttons are not displayed when My Project option is selected in Work Manager

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/work-manager#1048] opened 2021-01-21 04:10 UTC
### Expected behavior
Not sure about this behavior but don't see any reason to not show the buttons until My Projects option is selected/deselected

### Actual behavior
The 'Launch new', 'View project in connect' and 'View project in direct' buttons are not displayed until My Project option is selected/deselected

### Steps to reproduce the problem
- Go to https://challenges.topcoder.com/projects/{projectId}/challenges
- The buttons are not displayed
- Now select/deselect the My project option(depending on it's current status)
(Now the Launch New button appears)
- If you again select/deselect the My Project option, the buttons are still there

### Screenshot/screencast
https://user-images.githubusercontent.com/4592712/105278010-a2560580-5bca-11eb-8b05-65b6d4c4214b.mp4

#### Environment
- OS: Windows 10
- Browser: Chrome 87.0.4280.141
- User role: Copilot

**Comment by maxceem** [comment] 2021-02-19 10:29
@sdgun I cannot reproduce this issue. Could you please check if you still can reproduce it?

**Comment by sdgun** [comment] 2021-02-25 12:48
@maxceem This is not happening anymore to me.

**Comment by maxceem** [comment] 2021-02-25 12:52
@vikasrohit I guess we can close it then, right?

**Closed** 2021-02-25 13:48 UTC
Labels: Could not reproduce, Release Due Date: 3/12
