### ISSUE TITLE
Popup message or toaster is missing to notify user if there is any server side error

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/work-manager#823] opened 2020-09-18 11:54 UTC
**Pre Condition**
Challenge API should not working as expected or it has to some error on API.

**To Reproduce / Actual Behavior**

1. Go to challenge listing page [draft tab]
2. Try to activate the challenge.

**Expected behavior**
System should notify to user with informative message if there is any server side error.

**Reference **
Please go through this issue :
https://github.com/topcoder-platform/challenge-engine-ui/issues/821

![image](https://user-images.githubusercontent.com/25297859/93594552-c5329c00-f9d5-11ea-866e-9115175642ea.png)

**Comment by codejamtc** [comment] 2020-09-21 14:51
@drasticdpk I am not getting this, please double check if you get a chance, Thanks

**Comment by drasticdpk** [comment] 2020-09-22 02:34
FYI : It is negative testing.   
Here we need valid/proper message. Why user unable to activate it ?
"Unable to activate the challenge" >> This may not enough.
Reference : 
![image](https://user-images.githubusercontent.com/25297859/93839290-34e1a900-fcac-11ea-87eb-a753354c4ba6.png)

**Comment by vikasrohit** [comment] 2020-09-28 14:29
@drasticdpk this error is displayed when we don't know the exact error. 😬 

However, we just found the issue behind this generic error. It should be fixed in dev in 10 minutes.

**Comment by drasticdpk** [comment] 2020-09-29 02:24
Verified on Dev Mode 
Reference:
![image](https://user-images.githubusercontent.com/25297859/94505518-fbb8b400-022a-11eb-9f72-cc226275cc21.png)
![image](https://user-images.githubusercontent.com/25297859/94505547-0b37fd00-022b-11eb-85cf-68aefec1f7e2.png)

**Comment by vikasrohit** [comment] 2020-09-29 04:14
@drasticdpk the second screenshot shows error, do you want to convey any issue with it?

**Comment by drasticdpk** [comment] 2020-09-29 16:40
@vikasrohit , this is our expectation.  i.e use is getting complete message if there is any error on server side.

**Comment by vikasrohit** [comment] 2020-09-30 04:15
okay. However, I would still like you to understand that the error message `Unable to Activate the challenge` is rendered when the application itself is not able to understand the error. That means, that itself is not a bug or wrong however, we should definitely need to understand the root cause behind such situations when this error is rendered.

**Comment by sandhiyakavi** [comment] 2020-11-20 09:35
Verified on Prod.Working as expected.

![image](https://user-images.githubusercontent.com/55895538/99784394-163e4800-2b5f-11eb-9339-f9ab1ca7fdc4.png)

**Closed by sandhiyakavi** 2020-11-20 09:35 UTC
Labels: P3, QA Pass in Dev, QA Pass in Prod
