### ISSUE TITLE
pureV5 Task NDA Required Even When Not Selected

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/work-manager#1143] opened 2021-05-05 15:54 UTC
In dev:
1. Project has NDA required
2. Create a Development Task
2. On the details page, the NDA radio button is selected by default

<img width="384" alt="Screen Shot 2021-05-05 at 11 52 21 AM" src="https://user-images.githubusercontent.com/5400156/117170848-5ce3cf80-ad98-11eb-98ef-03b675a31d79.png">

4. Select a member who hasn't signed the NDA (in this case, `jcori30`
5. Launch the challenge, correctly see the error:

<img width="886" alt="Screen Shot 2021-05-05 at 11 50 16 AM" src="https://user-images.githubusercontent.com/5400156/117171148-9f0d1100-ad98-11eb-95ae-786a8fb538d4.png">

6. Change the NDA radio button to NO, still see the error.

**Comment by lakshmiathreya** [comment] 2021-05-06 06:42
cc @drasticdpk @coderhacker

**Comment by drasticdpk** [comment] 2021-05-06 07:30
**Findings** 
1. Above issue valid 
2. Unable to find out Direct/OR link while hovering the challenge , please ignore this if this is expected. 
![image](https://user-images.githubusercontent.com/25297859/117251077-e14f5480-ae63-11eb-9241-2c9e2216be5e.png)
3. In dev env, does not found NDA ( in prod we can see ) 
![image](https://user-images.githubusercontent.com/25297859/117255485-6b4dec00-ae69-11eb-950a-59aacdebfd2c.png)

4. Edit button  should remove for completed task. 
  
![image](https://user-images.githubusercontent.com/25297859/117256362-50c84280-ae6a-11eb-95d5-172028c82bd9.png)

**Comment by lakshmiathreya** [comment] 2021-05-06 10:22
@drasticdpk - since this is Pure V5 and no legacy id - OR entry will not be there. For Edit button - can you log a different issue?

**Comment by drasticdpk** [comment] 2021-05-06 13:38
Ok noted @lakshmiathreya .

**Comment by mirzailhami** [comment] 2021-05-15 05:45
@vikasrohit it always send the same payload either with or without NDA required to `https://api.topcoder-dev.com/v5/resources`.

For example:
```
{challengeId: "99b9f329-f3d1-40da-a8e1-aded0aefcb20", roleId: "732339e7-8e30-49d7-9198-cccf9451e221",…}
challengeId: "99b9f329-f3d1-40da-a8e1-aded0aefcb20"
memberHandle: "jcori30"
roleId: "732339e7-8e30-49d7-9198-cccf9451e221"
```

The API checked whether the user has been agreed or not:
https://github.com/topcoder-platform/resources-api/blob/develop/src/services/ResourceService.js#L252-L254
As you can see it always check the agreement of the assigned member.

Solution:
It should send NDA true/false to the `https://api.topcoder-dev.com/v5/resources` so it will trigger function `checkAgreedTerms ` should be call or not.

**Comment by vikasrohit** [comment] 2021-05-16 04:59
No @mirzailhami I don't think we need to do anything with resources api. Challenge API automatically validates the assigned members' terms when we try to save the challenge. All we need to make sure is that when NDA is turned off, it should remove the NDA term from the terms array of the challenge object when it POST/PATCH data after user has made changes to the edit form.

**Comment by mirzailhami** [comment] 2021-05-16 07:24
> No @mirzailhami I don't think we need to do anything with resources api. Challenge API automatically validates the assigned members' terms when we try to save the challenge. All we need to make sure is that when NDA is turned off, it should remove the NDA term from the terms array of the challenge object when it POST/PATCH data after user has made changes to the edit form.

It calls POST /resources when you click `Save Draft`, with this payload.

```
{"challengeId":"1bfc1352-2568-4f99-b0fc-f29b6260b75d","roleId":"732339e7-8e30-49d7-9198-cccf9451e221","memberHandle":"jcori30"}
```

![Screen Shot 2021-05-16 at 14 19 54](https://user-images.githubusercontent.com/8240895/118389018-eb3a3a00-b651-11eb-8b23-18936e95df99.png)

How do we remove the NDA term from the terms array of the challenge? Do you mean we should call POST /challenges without terms array in payload first, before calling POST /resources when creating challenge?

**Comment by vikasrohit** [comment] 2021-05-16 11:56
@mirzailhami Please see this [code](https://github.com/topcoder-platform/work-manager/blob/develop/src/components/ChallengeEditor/index.js#L587-L606). This piece of code is trying to remove the NDA terms from the terms array on uncheck of NDA (or choosing `No` of the radio button), but this piece is not working. We have to figure out that to fix the issue. I think some thing is going on with the way radio button works. I mean originally, I think we had a checkbox instead of Radio button which is why the event handler says `toggleNDARequire` and when we redesigned it to be a radio button, this event handler was not verified, I guess and that might be causing the issue. My theory is that `toggeNDARequire` is not firing or if it is, it is not doing what it should.

**Comment by mirzailhami** [comment] 2021-05-16 22:25
@vikasrohit that function worked. On button `Save Draft` clicked, it called `/resources` first, then `/challenges`, that caused the errors. I sent commit for fixes.

![Screen Shot 2021-05-17 at 05 22 09](https://user-images.githubusercontent.com/8240895/118414625-f8960980-b6cf-11eb-8574-011a665b7169.png)

**Comment by vikasrohit** [comment] 2021-05-17 04:34
@mirzailhami good catch. but I think there was a reason why we are saving the challenge details after saving resources. I am not able to recall, but there was some issue if do challenge update first and resource later. I am thinking through it but there is definitely some regression to be there if we merge this change.
Ideally, we want all of the API calls to update their respective resources in a transaction but that is not possible on front end that is why we are limited in terms of options.

**Comment by mirzailhami** [comment] 2021-05-17 05:25
@vikasrohit before this commit, only updateResource for submitter function called before updateChallenge. All other updateResource function called after updateChallenge.

**Comment by vikasrohit** [comment] 2021-05-17 05:53
Ohk, that makes sense. I think earlier we were saving resources first and if there was any error in it, the challenge update used to fail. So, what we did is to save challenge first and then do resource management so that challenge changes are saved first and in case there is any error in resource updates after it, user can always retry from Work Manager to update the resource (i.e. update copilot or reviewer or submitter if it failed) or ask support to add resources.
So, I guess we are good for now. btw, we do have feature branch for work manager as well. But I guess you merged changes directly to dev, and there is only one other change in the feature branch, I am merging the feature branch into develop now.

**Comment by vikasrohit** [comment] 2021-05-17 06:01
@drasticdpk this is also ready for QA.

**Comment by coderhacker** [comment] 2021-05-17 07:24
QA Comments: This is failed on DEV, please find the attached video for all scenarios: 


https://user-images.githubusercontent.com/62358241/118447575-96102e00-b70e-11eb-8709-55ce0084266c.mp4

**Comment by mirzailhami** [comment] 2021-05-17 08:27
@coderhacker @vikasrohit I followed the steps to reproduce based on issue detail above, without Groups. 

https://user-images.githubusercontent.com/8240895/118457706-3a509f80-b724-11eb-8ab7-6f21211b33bf.mov

**Comment by vikasrohit** [comment] 2021-05-17 09:16
@coderhacker it is very long video for the purpose of validation of the issue. I think issue is fixed and is working as expected even in your video. I can see that when you tried to assign the task to a member, it showed you error of terms for two terms (one NDA and another Standard terms) and as soon as you selected `No` from the NDA question, it reduced the terms to be accepted by the assigned member i.e. now I can see only Standard terms in the error.
So, it is working as expected. What we want is that if user Selects `No` for NDA, he/she should not see the terms error for the NDA terms, if user has not accepted the Standard terms, it would continue to show that term error because every member has to accept the standard terms in order to work on any task or challenge.

**Comment by vikasrohit** [comment] 2021-05-17 09:19
@mirzailhami I think in your video you tried to assign the task to your self, and you might have already accepted the NDA terms, that is why it is not giving any error whether you choose Yes or No for the NDA question. So, please choose a user who hasn't signed the NDA terms and then you should see the validation error for the Yes answer for NDA question and you should not see the error when No is selected as the answer for NDA question.

**Comment by coderhacker** [comment] 2021-05-17 09:38
@vikasrohit thanks for the update.  Passed on Dev

**Comment by coderhacker** [comment] 2021-05-18 10:15
This is passed on Production: Please see attached video

https://user-images.githubusercontent.com/62358241/118634247-f2974a00-b7ef-11eb-9c80-8a919bcecff9.mp4

**Closed by coderhacker** 2021-05-18 10:15 UTC
Labels: Dev Environment, P1, Prod Environment, QA Pass in Dev, QA Pass in Prod, released

**Comment by vikasrohit** [comment] 2021-05-18 12:21
@rootelement it is fixed and deployed to prod, please let us know if you still see the issue.
