### ISSUE TITLE
Challenge is stalled after activating the challenge

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#852] opened 2020-10-05 06:36 UTC
![image](https://user-images.githubusercontent.com/42398485/95047091-0ed3f400-0703-11eb-9c1c-e4f4b0061855.png)

![image](https://user-images.githubusercontent.com/42398485/95047129-1dbaa680-0703-11eb-8116-b3769d8d3e54.png)

### Steps to reproduce the problem

URL: https://challenges.topcoder-dev.com/projects/16604/challenges/7f4daa1a-83d6-4833-bdaf-1fd3e24d845e/view

1. Open https://challenges.topcoder-dev.com/ and login as Copilot
2. Select a project from the list 'Connect Project 01 - codejam'
3. Create a Dev challenge (Set date as Today and time as 15min later time)
4. Click Edit
5. Click Launch as Active > Confirm
6. Wait few mins for sync
7. Go to Active tab and check

### Actual behavior
- Challenge is stalled after activating the challenge

### Expected behavior
- Should display the phase details properly

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.121
**- User role (client, copilot or manager):** Copilot
**- Account used:**  `TCConnCopilot`

**Comment by codejamtc** [comment] 2020-10-05 06:49
Challenge details: https://www.topcoder-dev.com/challenges/7f4daa1a-83d6-4833-bdaf-1fd3e24d845e

**Comment by vikasrohit** [comment] 2020-10-06 12:04
Auto pilot is not working in dev environment so it is not moving the phases of the challenges.

**Comment by acshields** [comment] 2020-11-18 15:16
@vikasrohit - reading through your note to codejam, it seems like this isn't a real issue and we can close, correct?

**Comment by vikasrohit** [comment] 2020-11-19 07:39
Yes, that is my understanding but it has not been vetted by QA yet for the same, that is why I moved it back to requirement clarification state.

**Comment by acshields** [comment] 2020-11-19 14:01
@lakshmiathreya - Can someone test this in PROD and identify whether this is a real issue? It seems that codejam initially did this test in DEV and encountered the stalling because Autopilot is not activated there.

**Comment by sandhiyakavi** [comment] 2020-11-25 06:07
@vikasrohit @acshields Tested in Prod. Still the challenge is getting stalled after activating it

Challenge url: https://challenges.topcoder.com/projects/24943/challenges/6d4a3448-7171-4710-b245-e4ea3c315408/view

![image](https://user-images.githubusercontent.com/55895538/100189482-bf09f000-2f2f-11eb-86b1-7ed3d5675d27.png)
![image](https://user-images.githubusercontent.com/55895538/100189541-d3e68380-2f2f-11eb-897d-a96d34010e79.png)

**Comment by acshields** [comment] 2020-11-30 17:07
@vikasrohit - Adding this to the December backlog.

**Comment by rootelement** [comment] 2020-12-01 16:34
I really don't think this is anything to do with Work Manager or Challenge API. If you launch a challenge in direct it sometimes takes a while to get picked up by autopilot. Does the challenge ever get moved active in this case? 10 min? 20 min? If so, then our mechanisms are working correctly.

Please keep in mind as well that:
1. Autopilot is never really on time.
2. v4 ES Feeder needs to pick up the changes and put it in ES
3. Legacy -> v5 sync comes through every minute and checks for changes. If there's a change, it queues it for sync
4. v5 sync comes through every 2 minutes and syncs the challenge forward.

If it takes autopilot 10 min to pick up the phase change, that could be 10min + 1min + 1min + 2min to sync forward.

**Comment by vikasrohit** [comment] 2020-12-03 06:15
@sandhiyakavi Can you please reconfirm if the issue is transient only as per https://github.com/topcoder-platform/work-manager/issues/852#issuecomment-736667326?

@acshields we can close this if @sandhiyakavi finds it transient.

**Comment by sandhiyakavi** [comment] 2020-12-03 10:16
@vikasrohit Created another challenge to check. It took **nearly one hour and forty minutes** to change from stalled to Registration status.

![image](https://user-images.githubusercontent.com/55895538/100995973-dda96000-359b-11eb-8b8f-6743e0bfd2bd.png)

**Comment by vikasrohit** [comment] 2020-12-03 10:24
Thanks @sandhiyakavi for the retest. I think the challenge's start date is one hour from the creation time, so that might be the primary reason of the delay. Are you seeing any deviation from the start date that you are setting while challenge creation? I mean is it taking longer than the start date of the challenge to reflect the actual phase?

**Comment by sandhiyakavi** [comment] 2020-12-03 13:37
@vikasrohit I tried with another challenge ,The start date was set as today's date with 20:30 time. Below screenshot taken after activating the challenge.

challenge url: https://challenges.topcoder.com/projects/24943/challenges/d5c461a6-ec39-4489-b1f0-dd4adfe8df24/view
<img width="960" alt="screen1" src="https://user-images.githubusercontent.com/55895538/101023659-6cc37180-35b6-11eb-8b25-695a06dbbcbc.png">

It's been 2 hrs the challenge is still in stalled phase.

![image](https://user-images.githubusercontent.com/55895538/101024322-4520d900-35b7-11eb-8e91-96f1f67b9d1d.png)

In OR
![image](https://user-images.githubusercontent.com/55895538/101024374-5d90f380-35b7-11eb-84d1-4611965766af.png)

I think the start date in WM is getting updated once the registration phase starts. Will confirm it once this challenge's registration phase starts.

**Comment by sandhiyakavi** [comment] 2020-12-04 04:16
@vikasrohit The challenge's Registration phase started. The start date is also updated according to that.

![image](https://user-images.githubusercontent.com/55895538/101121150-c23d6400-3632-11eb-9ee4-9e0c2c2190cf.png)
![image](https://user-images.githubusercontent.com/55895538/101121175-d6816100-3632-11eb-9ec0-f21a71033e5d.png)

**Comment by vikasrohit** [comment] 2020-12-04 10:23
@sandhiyakavi I think there is some mistake in timezone calculation. I mean you set the challenge start date to be `December 3, 2020 20:30 IST` while the OR is showing first phase start time as `December 3, 2020 06:30 EST` which should have been `December 3, 2020 10:00 AM EST`. I am trying to do more investigation in this direction. Please let me know if you also see any mismatch in timezone calculation.

**Comment by sandhiyakavi** [comment] 2020-12-04 10:41
@vikasrohit Actually, Time zone calculation is correct. I set the challenge start date as December 3, 2020 20:30 **JST** . I am following Japan timezone (since I am in Japan) that's why it is showing like that.

**Comment by vikasrohit** [comment] 2020-12-04 11:21
Ohk. I don't know why I assumed IST for you. No worries, if timezone calculation is correct, I guess we are good. Current auto. pilot has some limitations in terms of processing all challenges to be launched. It can skip a challenge for starting even though it is legit time for it to start. So, do you think now we can close this issue?

**Closed** 2020-12-04 11:37 UTC
Labels: 12/15 ES Release, Dev Environment, Functional, auto-pilot-issue
