### ISSUE TITLE
Unable to update Challenge 

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/work-manager#806] opened 2020-09-14 11:24 UTC
**Steps **
1. Go to https://challenges.topcoder.com/projects/24943/challenges/42180746-0001-456b-b818-819510e4d1c1/edit
2. Edit Something and try to save it.

**Reference : **
![image](https://user-images.githubusercontent.com/25297859/93079994-c188d780-f6ac-11ea-9ae2-630aaf86d985.png)

**Comment by vikasrohit** [comment] 2020-09-15 03:42
@drasticdpk @codejamtc it is duplicate of #776

**Comment by codejamtc** [comment] 2020-09-15 15:08
@vikasrohit I guess this is something to do with the `HTML` code generated when the user saves the changes using the Direct and then comes to the WM and try to edit something and save. But I will investigate more and let you know

**Comment by vikasrohit** [comment] 2020-09-16 11:54
> When the user creates a challenge using the WM and activates it will activate the challenge and move the challenge into the Active tab and remove it from the Draft but after 10-15min it will move the challenge to the Draft tab again

@codejamtc @lakshmiathreya these are the symptoms of data reset that I am talking about since very long. This is a P0 to be solved. @codejamtc if you can reproduce it predictably, it would be great. That would help us in debugging the issue.

fyi @rootelement 

> After a few mins, the challenge will activate again and posted but you will see the challenge in both Active and Draft tabs. So then if the user tries to edit the challenge in the Draft tab you will get that validation message again.

This might be a stale UI and should not be there once you switch tabs. However, for you particular issue, I think there are two different challenges on production with the same name in the same project. You can verify that by looking at their GUID.

**Comment by ThomasKranitsas** [comment] 2020-09-18 10:02
This is a frontend issue.

For example, using this challenge `https://challenges.topcoder-dev.com/projects/9171/challenges/d1bf36f2-0f8a-47ee-845e-c6212c531b4f/edit`

The validation method checks for `_.isEmpty(this.state.currentTemplate)` which in this case is `undefined` so the validation does not pass.

**Comment by vikasrohit** [comment] 2020-09-18 16:03
Yep I am aware of that @ThomasKranitsas and I mentioned that I can fix that but I have kept it just to validate the theory of data reset. Because what is happening behind the scene is that some how the `timelineTemplateId` is being set to a wrong timeline template id, rather it is being set to a ChallengeTimelineTemplateId id and that is what @rootelement debugged last week. So, we need to identify who is setting the `timelinTemplateId` wrong.

**Comment by vikasrohit** [comment] 2020-09-22 03:27
@ThomasKranitsas @rootelement do we know who is polluting the `timelineTemplateId` of a challenge? Please note from https://github.com/topcoder-platform/challenge-engine-ui/issues/806#issuecomment-692778858 that there are other fields as well which are being overridden somehow.

**Comment by ThomasKranitsas** [comment] 2020-09-22 18:30
@rootelement that was the sync tool we fixed a few days back, right?

**Comment by vikasrohit** [comment] 2020-09-23 06:57
@drasticdpk @codejamtc @lakshmiathreya should be ready for QA in dev as the root cause which was preventing the challenge to be updated is fixed in the migration script which was messing with `timelinteTemplateId` of the challenge. However, the other field that are being reset or lost, should be tracked separately as I don't think they were present in the original description of the issue and it confuses us to have multiple issues in single ticket.

**Comment by lakshmiathreya** [comment] 2020-09-23 07:05
@vikasrohit we will log an Issue per field since the source of error might be different in each case right?

**Comment by vikasrohit** [comment] 2020-09-23 07:33
Theoretically yes, but I was not anticipating source of each field would be different because that would be most difficult to debug and fix.
BTW, there are already couple of issues regarding data reset:

https://github.com/topcoder-platform/challenge-engine-ui/issues/804
https://github.com/topcoder-platform/challenge-engine-ui/issues/817
https://github.com/topcoder-platform/challenge-engine-ui/issues/795

**Comment by drasticdpk** [comment] 2020-09-28 03:31
Verified on Dev env.
Reference 
![image](https://user-images.githubusercontent.com/25297859/94387791-eb410480-016a-11eb-81eb-c524c3167558.png)
Note : For now I have not created separate issue , we will re-test the flow once above listed issue is solved.

**Comment by vikasrohit** [comment] 2020-09-28 06:26
@drasticdpk for clarity, could you please specify for what part you wanted to create separate issue? If you are concerned about data not being synced to legacy or specific fields being lost after sync, I guess we have multiple issues logged for them already.

**Comment by drasticdpk** [comment] 2020-09-28 06:39
@vikasrohit 
FYI : currently I don't have have  any specific issue.

**Comment by sandhiyakavi** [comment] 2020-11-20 08:49
Verified on Prod. Working as expected.

**Closed by sandhiyakavi** 2020-11-20 08:49 UTC
Labels: Functional, P0, Prod Environment, QA Pass in Dev, QA Pass in Prod
