### ISSUE TITLE
Shape pure v5 task - related changes 

### ISSUE THREAD

**Issue by sachin-maheshwari** [topcoder-platform/work-manager#1088] opened 2021-02-27 16:34 UTC
For this shapeup project, we need to send additional flag "pureV5Task" flag during creating a "task". Due to this flag backend will not dependent on legacy system sync (not need legacy challenge id). 

For above changes, we are expecting following corresponding UI changes for "task" : 

- Remove the Direct and Online Review buttons from the Challenge View and Listing pages 
- Make the Launch button enabled as soon as we create a "task", because it doesn’t have to wait for legacy challenge id
- Launch button should change "task" status to Active
- When Active, the button should say “Close Task”

**Comment by lakshmiathreya** [comment] 2021-02-28 04:28
@drasticdpk this has to be deployed tomorrow. I am doing regression - can you also spend some time on this today if possible. Thx!

**Comment by drasticdpk** [comment] 2021-02-28 05:29
>  Remove the Direct and Online Review buttons from the Challenge View and Listing pages
![image](https://user-images.githubusercontent.com/25297859/109408718-35494300-79b4-11eb-90e5-f68c21cfad8b.png)
![image](https://user-images.githubusercontent.com/25297859/109408732-5f9b0080-79b4-11eb-96d5-133448e40e82.png)

>Make the Launch button enabled as soon as we create a "task", because it doesn’t have to wait for legacy challenge id

OK 
![image](https://user-images.githubusercontent.com/25297859/109408771-d0421d00-79b4-11eb-8251-cc1bfc219f92.png)

Launch button should change "task" status to Active 
> Ok
When Active, the button should say “Close Task”
> Ok
![image](https://user-images.githubusercontent.com/25297859/109408851-89a0f280-79b5-11eb-9634-8829b6068699.png)

@sachin-maheshwari , here is the verification for above. However we are unable to create task for project level user. Can you please help us to setup NDA here.  cc @lakshmiathreya 
https://www.topcoder-dev.com/challenges/terms/detail/e5811a7b-43d1-407a-a064-69e5015b4900

**Comment by lakshmiathreya** [comment] 2021-02-28 05:48
Unable to test NDA based Tasks due to this https://github.com/topcoder-platform/work-manager/issues/1089

**Comment by sachin-maheshwari** [comment] 2021-02-28 05:52
@lakshmiathreya I am not sure about NDA.

**Comment by drasticdpk** [comment] 2021-02-28 05:54
FYI https://topcoder.slack.com/archives/C0125BH1A2W/p1614491135049100 cc @vikasrohit

**Comment by lakshmiathreya** [comment] 2021-03-01 12:23
@sachin-maheshwari pls note another Issue noticed for Specifically the Pure V5 Tasks: Winner tab throws up the following error:
<img width="1680" alt="Screenshot 2021-03-01 at 5 51 04 PM" src="https://user-images.githubusercontent.com/51733042/109496633-ed5f1480-7ab6-11eb-86f0-05a1f61a4359.png">
<img width="1680" alt="Screenshot 2021-03-01 at 5 51 21 PM" src="https://user-images.githubusercontent.com/51733042/109496647-f223c880-7ab6-11eb-9bd1-209e6efc93b0.png">
<img width="1680" alt="Screenshot 2021-03-01 at 5 49 05 PM" src="https://user-images.githubusercontent.com/51733042/109496605-e3d5ac80-7ab6-11eb-9393-c22ef0414a39.png">

**Comment by sachin-maheshwari** [comment] 2021-03-02 04:54
@lakshmiathreya i think that should be community-app issue. For pervious challenges its coming ? 
@rootelement  any idea ?

**Comment by lakshmiathreya** [comment] 2021-03-02 05:07
<img width="1680" alt="Screenshot 2021-03-02 at 10 35 06 AM" src="https://user-images.githubusercontent.com/51733042/109600415-15945500-7b43-11eb-81a8-1dd70f04870e.png">

**Comment by lakshmiathreya** [comment] 2021-03-02 06:57
cc @luizrrodrigues

**Comment by drasticdpk** [comment] 2021-03-02 07:58
Verification for project level NDA

 
![image](https://user-images.githubusercontent.com/25297859/109616380-2f429600-7b5d-11eb-9d56-8657cf6d69af.png)

**Comment by lakshmiathreya** [comment] 2021-06-02 10:17
@coderhacker @drasticdpk the winner tab issue is now fixed https://github.com/topcoder-platform/community-app/issues/5529 - please verify this Issue - mark it pass and close it.

**Comment by coderhacker** [comment] 2021-06-02 11:11
This is passed on to production, please find attached evidence

https://user-images.githubusercontent.com/62358241/120470438-23b37500-c3c1-11eb-9a10-3095126e5e5f.mp4

**Closed by coderhacker** 2021-06-02 11:11 UTC
Labels: Dev Environment, Feature: Miscellaneous, Have A Question (Dev), Prod Environment, QA Partially reviewed in Dev, QA Pass in Prod
