### ISSUE TITLE
Ability to delete a task

### ISSUE THREAD

**Issue by huangqun** [topcoder-platform/work-manager#1014] opened 2020-12-21 15:29 UTC
### Expected behavior
There should be a way to delete a task.

### Actual behavior
Right now after a task is created, there's no way to delete it, even if for some reason the task fails to create the legacy challenge and therefore cannot be closed in the normal way.

**Comment by vikasrohit** [comment] 2021-01-05 11:50
@acshields we don't yet have delete feature in general for any challenge. How do you want to proceed with this? What would be the rules for deleting the challenges? For reference we have delete feature logged here #873

**Comment by acshields** [comment] 2021-01-05 13:47
@vikasrohit - your response suggests that getting to a "delete" capability will take more than two weeks for us to get to the requirements/an implemented solution. I will deprioritize this for now, and instead will look to prioritize it later as a project.

**Comment by vikasrohit** [comment] 2021-01-07 11:06
@acshields I didn't mean that it would take more time. I meant is that we need to come up with business rules for which deletion would be allowed. I think API already has this capability and has its own rules but question is that are we on same page for those rules? There might be no such rule at all, I am just conveying that we need to discuss on that with @rootelement

**Comment by vikasrohit** [comment] 2021-01-19 10:01
@acshields @huangqun we added the capability (#927) to delete any challenge that is in `New` status. Closing the issue for now, please feel free to reopen it if the new functionality is not what was intended in this request.

**Closed by vikasrohit** 2021-01-19 10:01 UTC
Labels: Requirement Question
