### ISSUE TITLE
After activating a challenge; the challenge moves to draft after sometime 

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#827] opened 2020-09-23 14:11 UTC
### Steps to reproduce the problem

1. Open https://challenges.topcoder-dev.com/ and login as Admin
2. Select a project from the list 'Test v5 {codejam} - 0001'
3. Create a Dev challenge with all the details and save as draft
4. Click Edit
5. Activate the challenge (You will see the challenge in Active tab; but wait for 5-10min)
6. Check the active tab again

### Actual behavior
- After activating a challenge; the challenge moves to draft after sometime 

### Expected behavior
- Should display the challenge on the active tab

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Copilot
**- Account used:**  `copilot_codejam`

**Comment by rootelement** [comment] 2020-10-19 16:23
Duplicate of https://github.com/topcoder-platform/challenge-engine-ui/issues/827?

**Comment by vikasrohit** [comment] 2020-10-20 06:28
> Duplicate of #827?

@rootelement did you meant some other issue? Here is referring to the same issue itself.

**Closed** 2020-11-27 10:20 UTC
Labels: Functional, P1, QA Pass in Prod
