### ISSUE TITLE
[$20] Work Manager: Link to submission review app when clicking submission count in WM

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#1168] opened 2021-06-10 05:13 UTC
Once we add the count of submissions to Challenge view page, we should add link to it which takes user to the submission review app.

**Comment by phead198708** [comment] 2021-06-23 08:59
add a link to submission review app on last column in submission table (Initial / Final Score column). The format of the submission review app link is https://submission-review.topcoder.com/challenges/{{challenge id}}/submissions/{{submission id}}, the sample is: https://submission-review.topcoder.com/challenges/30187830/submissions/e7e355f1-5ee4-42dd-9360-c912e27c0d35

**Comment by phead198708** [comment] 2021-06-23 09:05
add a text (Manage Submissions) with link above submission table. and the link format is https://submission-review.topcoder.com/challenges/{challenge id}. the sample is https://submission-review.topcoder.com/challenges/30187830

![View Details 2021-06-23 17-04-01](https://user-images.githubusercontent.com/85940583/123069312-3f9cba80-d445-11eb-88bf-0da18f1350a0.png)

**Comment by phead198708** [comment] 2021-06-23 09:07
@yoution pls check this one.

**Comment by yoution** [comment] 2021-06-23 09:32
@phead198708 please assign to me

**Comment by vikasrohit** [comment] 2021-06-23 09:54
> add a text (Manage Submissions) with link above submission table. and the link format is [https://submission-review.topcoder.com/challenges/{challenge](https://submission-review.topcoder.com/challenges/%7Bchallenge) id}. the sample is https://submission-review.topcoder.com/challenges/30187830
> 
> ![View Details 2021-06-23 17-04-01](https://user-images.githubusercontent.com/85940583/123069312-3f9cba80-d445-11eb-88bf-0da18f1350a0.png)

@phead198708 I think you mistakenly shown the wrong tab. We need the link under `Submissions` tab not `Registrations`

**Comment by phead198708** [comment] 2021-06-23 09:57
yes. @vikasrohit  thanks for point it out. @yoution  pls notice we need to add this text link to submission tab only. The position above is correct.

**Comment by phead198708** [comment] 2021-06-23 10:04
Challenge https://www.topcoder.com/challenges/07b0c73a-5dd0-460d-81ab-b8dd2c18d974 has been created for this ticket.<br/><br/>```This is an automated message for phead via Topcoder X```

**Comment by phead198708** [comment] 2021-06-23 10:04
Challenge https://www.topcoder.com/challenges/07b0c73a-5dd0-460d-81ab-b8dd2c18d974 has been assigned to yoution.<br/><br/>```This is an automated message for phead via Topcoder X```

**Comment by yoution** [comment] 2021-06-23 10:34
@phead198708 please review https://github.com/topcoder-platform/work-manager/pull/1193

**Comment by yoution** [comment] 2021-06-23 10:35
@bug-bash-helper https://github.com/topcoder-platform/work-manager/pull/1193 is ready for review

**Comment by coderhacker** [comment] 2021-06-25 09:50
It's blocking to verify due to regression issue https://github.com/topcoder-platform/work-manager/issues/1198

**Comment by vikasrohit** [comment] 2021-06-25 14:22
@coderhacker @drasticdpk as now we have verified the #1169 for existing challenge, I guess we can verify this one as well using the same principle.

**Comment by coderhacker** [comment] 2021-06-28 12:58
This is passed on to production.
https://user-images.githubusercontent.com/62358241/123640049-68a2be00-d83e-11eb-91fd-fd2ecf621cb3.mp4

**Comment by phead198708** [comment] 2021-06-28 12:58
Payment task has been updated: https://www.topcoder.com/challenges/07b0c73a-5dd0-460d-81ab-b8dd2c18d974
*Payments Complete*
Winner: yoution
Copilot: phead
Challenge `07b0c73a-5dd0-460d-81ab-b8dd2c18d974` has been paid and closed.<br/><br/>```This is an automated message for phead via Topcoder X```

**Closed by coderhacker** 2021-06-28 12:58 UTC
Labels: CF, Feedback, P2, QA Pass in Prod, tcx_Assigned, tcx_FixAccepted
