### ISSUE TITLE
After activating a Task; NDA, Assigned Member, Groups, Copilot and Copilot fee data is lost

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#817] opened 2020-09-16 18:24 UTC
![image](https://user-images.githubusercontent.com/42398485/93376816-ca4dea80-f81f-11ea-976f-fdeda56629d1.png)
![image](https://user-images.githubusercontent.com/42398485/93376862-da65ca00-f81f-11ea-8fe1-49a74ff02f56.png)

### Steps to reproduce the problem

1. Open https://challenges.topcoder.com/ and login as codejam
2. Select a project from the list 'Q2: Customer Experience Prod/Dev Delivery (Connect Projects)'
3. Create a draft task and Activate it 
4. Wait until it appears on the active tab
5. Open the task and click Edit
6. Check the NDA, Assigned Member, Copilot and Copilot fee

### Actual behavior
- After activating a Task; NDA, Assigned Member, Copilot, Groups and Copilot fee data is lost

### Expected behavior
- Should not lose any data while the sync is happening

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Copilot
**- Account used:**  `codejam`

**Comment by vikasrohit** [comment] 2020-09-17 11:10
@codejamtc root cause and symptoms are same as #806 and #776. Do you think that it is different from them? If not, we can close this one.

**Comment by codejamtc** [comment] 2020-09-17 12:47
@vikasrohit I will leave this as it is for tracking purpose

**Comment by rootelement** [comment] 2020-10-19 16:24
This will be fixed with this issue:
https://github.com/topcoder-platform/challenge-api/issues/330

**Comment by drasticdpk** [comment] 2020-12-11 10:55
Verified. 
![image](https://user-images.githubusercontent.com/25297859/101894490-59279480-3bce-11eb-993f-65f989ec367d.png)

Note: While closing the task, The reviewer fee and copilot  fee will exclude by system. i.e no need to pay for them.
( This is how we are doing from direct) 
Reference :
 https://www.topcoder.com/thrive/articles/How%20To%20Make%20Payments%20Through%20Direct

@vikasrohit , In challenge details, group name is showing as id instead of name can you please confirm it. 
cc @lakshmiathreya

**Comment by vikasrohit** [comment] 2020-12-11 12:12
> @vikasrohit , In challenge details, group name is showing as id instead of name can you please confirm it.

Please feel free to log separate issue for it.

**Comment by drasticdpk** [comment] 2020-12-11 15:52
Noted @vikasrohit .

**Closed** 2021-01-04 14:55 UTC
Labels: Functional, P0, Prod Environment, QA Pass in Prod
