### ISSUE TITLE
Tag, NDA and Review Type changes in Design challenge after activating it

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#850] opened 2020-10-05 04:30 UTC
[2.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5325230/2.zip)

### Steps to reproduce the problem

1. Open https://challenges.topcoder-dev.com/ and login as Copilot
2. Select a project from the list 'Connect Project 01 - codejam'
3. Create a Design challenge (Add NDA, Reviewer=Community; tag=Google)
4. Click Edit
5. Click Launch as Active > Confirm
6. Wait few mins for sync
7. Go to the Active tab and open the challenge and edit it
8. Check the NDA=Unchecked, Reviewer=Internal; tag=empty

### Actual behavior
- Tag, NDA and Review Type changes in Design challenge after activating it

### Expected behavior
- Should not change

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.121
**- User role (client, copilot or manager):** Copilot
**- Account used:**  `TCConnCopilot`

**Comment by vikasrohit** [comment] 2020-10-05 05:15
@codejamtc please share the challenge id or link to the challenge as well. It is difficult to trace the challenge with current information.

**Comment by vikasrohit** [comment] 2020-10-05 05:16
And I think it is duplicate of https://github.com/topcoder-platform/challenge-engine-ui/issues/817

**Comment by codejamtc** [comment] 2020-10-05 05:26
@vikasrohit In Dev challenges this is not happening but this is related to design challenges. Especially the `Reviewer` options change after activating it

**Comment by vikasrohit** [comment] 2020-10-05 05:39
Yes, these are the standard symptoms of the data reset which we are following since last two months. I think I shared this earlier as well that review type changes to `Internal` after some time challenge is saved (without activation) as well.
However, we might want to have separate issue for design track for tracking purposes. @lakshmiathreya your call.

**Comment by codejamtc** [comment] 2020-10-07 04:18
After activating the below data is lost during the sync cc @vikasrohit @lakshmiathreya 
- Tags 
- NDA
- Final Deliverables
- Stock Arts
- Submission Visibility
- Maximum Number of Submissions
- Copilot Fee
- Review Type

eg: https://challenges.topcoder-dev.com/projects/16604/challenges/bd4129ef-0fdc-4ee8-a468-4d71fe8e6903/view

**Comment by acshields** [comment] 2020-11-20 15:54
@vikasrohit - adding this to the december backlog. @lakshmiathreya - has this been retested recently for Design track?

**Comment by sandhiyakavi** [comment] 2020-11-25 07:57
@vikasrohit @acshields Retested the Design track. The added details were changed after some time of activation.Below are the observations.
1. NDA is still checked, Copilot Fee is not changed
2. Reviewer, Tags, Final deliverables, stock arts, Submission visibilitiy and Maximum Number of Submissions are changed

Challenge url: https://challenges.topcoder.com/projects/24943/challenges/29cecb6b-cc40-4a82-875f-028add62c9d4

![image](https://user-images.githubusercontent.com/55895538/100198081-b1a83200-2f3e-11eb-9f1a-f26deb357793.png)
![image](https://user-images.githubusercontent.com/55895538/100198166-d56b7800-2f3e-11eb-851e-ae22bcab5b4e.png)
![image](https://user-images.githubusercontent.com/55895538/100198203-df8d7680-2f3e-11eb-96a2-029836baa84a.png)

[issue#850_retest.zip](https://github.com/topcoder-platform/work-manager/files/5595164/issue.850_retest.zip)

**Comment by vikasrohit** [comment] 2020-11-26 11:57
@rootelement @acshields this is the same issue that we faced in the demo with mess last night.

**Comment by ThomasKranitsas** [comment] 2020-11-29 20:37
@rootelement this is how we're setting the `metadata` during sync 

https://github.com/topcoder-platform/legacy-challenge-migration-script/blob/c993874ed313c187b243b916d8531935f275aadc/src/services/challengeService.js#L734-L745

**Comment by lakshmiathreya** [comment] 2020-12-07 14:58
NDA, Review Type and other fields are lost after Sync in Prod.
<img width="1680" alt="Screenshot 2020-12-07 at 8 27 08 PM" src="https://user-images.githubusercontent.com/51733042/101366171-a0f6a500-38ca-11eb-9ef4-2aca2b6d3314.png">

**Comment by lakshmiathreya** [comment] 2020-12-16 13:42
@rootelement - NDA, Review Type, Reviewer, Copilot fee are retained now. Tag continues to be missed.
<img width="1680" alt="Screenshot 2020-12-16 at 7 07 20 PM" src="https://user-images.githubusercontent.com/51733042/102355849-6f6c9080-3fd2-11eb-99d0-4473a4bf7b5c.png"> 
<img width="1680" alt="Screenshot 2020-12-16 at 7 07 43 PM" src="https://user-images.githubusercontent.com/51733042/102355857-709dbd80-3fd2-11eb-801c-27f48fa092ff.png">

<img width="1680" alt="Screenshot 2020-12-16 at 7 06 35 PM" src="https://user-images.githubusercontent.com/51733042/102355835-6aa7dc80-3fd2-11eb-8a6c-791d0f4a9faf.png">

**Comment by lakshmiathreya** [comment] 2020-12-17 05:58
Since Tags is not relevant for Design Challenge. Moving this Issue to Pass.

**Comment by acshields** [comment] 2020-12-17 23:06
@lakshmiathreya @rootelement - can we call this one closed, then?

**Closed** 2021-01-04 14:53 UTC
Labels: 12/15 ES Release, API/Backend Question, Dev Environment, Duplicate, Functional, QA Pass in Prod, legacy-sync
