### ISSUE TITLE
Unable to assign task to a member in Work Manager

### ISSUE THREAD

**Issue by ketzjs09** [topcoder-platform/work-manager#1137] opened 2021-04-15 12:14 UTC
When creating a task, when I type someone's name in the _Assign To:_ section, no search results appear.

**Comment by vikasrohit** [comment] 2021-04-16 07:18
It works with handle only as of now.

**Comment by ketzjs09** [comment] 2021-04-16 08:54
Sorry, I meant handle. Nothing showed up when I entered the handle. It used to work the last time I checked a few days ago.

**Comment by vikasrohit** [comment] 2021-04-19 09:27
ohk. It might be temporary glitch with member api. As of now it is loading the possible handles matching the typed characters.

**Comment by vikasrohit** [comment] 2021-05-06 04:21
@ketzjs09 We have found the root cause for your problem. Please log a support ticket to add a copilot role to your handle. You are missing `copilot` role in your profile which is causing this trouble to you.

**Comment by vikasrohit** [comment] 2021-05-18 12:19
Closing the issue for now @ketzjs09 please feel free to reopen if you are still seeing the issue.

**Closed** 2021-05-18 12:19 UTC
Labels: no-work-needed
