### ISSUE TITLE
Work Manager: Show registrants/submissions on WM challenge page

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#1167] opened 2021-06-10 05:12 UTC
As we are showing count of registrants and submissions in Challenge listing page, we should show the same somewhere on the challenge view page.

**Comment by coderhacker** [comment] 2021-06-25 09:52
@vikasrohit how to verify this issue, could you please provide more information because I am unable to verify these changes due this regression issue https://github.com/topcoder-platform/work-manager/issues/1198

**Comment by vikasrohit** [comment] 2021-06-25 13:34
@coderhacker we have combined this issue with #1166 and #1169 i.e. you would see the registrants and submissions counts on their respective tabs on Challenge details page. This serves the original purpose of the issue.

**Comment by coderhacker** [comment] 2021-06-28 13:11
@vikasrohit  both issues fixed now on  production  #1166 and #1169 , so closing this ticket

**Closed by coderhacker** 2021-06-28 13:11 UTC
Labels: P2, QA Pass in Prod, Ready for QA
