### ISSUE TITLE
Unable to update challenge if there is any changes on copilot details.

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/work-manager#883] opened 2020-10-21 07:28 UTC
**Steps**
1. Go to https://challenges.topcoder-dev.com/projects/16640/challenges/f830624f-5588-4a5c-ba36-bd76c385be79/edit
2. Try to update the challenge by editing copilot name.

**Reference** : 
1.https://monosnap.com/file/Ru4QgykWm785rpCFbV1Efn2oVgi2lq
2.![image](https://user-images.githubusercontent.com/25297859/96686893-dd178a00-139e-11eb-81df-1c0a06544d8a.png)
3. ![image](https://user-images.githubusercontent.com/25297859/96686990-fe787600-139e-11eb-990c-a0c2339cbf59.png)

**Comment by vikasrohit** [comment] 2020-10-28 08:11
The challenge seems to be deleted now. @drasticdpk are you able to reproduce it on new challenge as well?

**Comment by drasticdpk** [comment] 2020-10-29 04:19
@vikasrohit ,
Never mind, we are having this issue for newly created challenge too. 
Mainly try to edit challenge by swapping copilot.
Reference : 
https://challenges.topcoder-dev.com/projects/9074/challenges/26beb2ff-b8a2-4ce8-8761-e5b17462d004/edit
![image](https://user-images.githubusercontent.com/25297859/97525001-fbe4d480-19cd-11eb-8cbb-75381a123bbe.png)

Note : Please follow this video to replicate the issue 
https://monosnap.com/file/Ru4QgykWm785rpCFbV1Efn2oVgi2lq

**Comment by vikasrohit** [comment] 2020-10-29 12:10
I think it is related to https://github.com/topcoder-platform/resources-api/issues/42#issuecomment-717963663

**Comment by vikasrohit** [comment] 2020-11-02 09:02
@drasticdpk It should be fixed now. It was happening because of https://github.com/topcoder-platform/resources-api/issues/42#issuecomment-719231246 as copilot was not able to see existing copilot and tempt to update the copilot for the challenge while there already exists a copilot.

**Comment by drasticdpk** [comment] 2020-11-02 10:14
@vikasrohit still having same same issue. Anything pending yet for deployment ?
![image](https://user-images.githubusercontent.com/25297859/97856314-3929c900-1d24-11eb-8bc4-7f8d2defffe0.png)

**Comment by vikasrohit** [comment] 2020-11-02 15:01
which user you are logged in @drasticdpk ? I tried with `TCConnCopilot` and it worked just fine for me for the same challenge.

**Comment by vikasrohit** [comment] 2020-11-04 11:30
@drasticdpk are you still facing the issue?

**Comment by drasticdpk** [comment] 2020-11-05 14:38
@vikasrohit ,
I am able to replicate the issue from my end.
here is the reference : https://monosnap.com/file/V8LYxGXiaaC2OTDBptjBrYBTAAfmGo
Note : try to swap copilot 2-3 times and save it. 
challenge : https://challenges.topcoder-dev.com/projects/16640/challenges/d2dae0a7-074f-48cb-9707-b96cde575c76/edit
User :  TCConnCopilot

**Comment by vikasrohit** [comment] 2020-11-09 11:19
@drasticdpk I think it is happening intermittently and my doubt is that it is happening because of sync timing. May be the time  you tried to change the copilot, it was added by sync for its previous operations. I have tried it multiple times with the same user and same challenge and it is working just fine for me every time. So, I think we can close this issue as the original issue is fixed (which was reproducible every time) and we can open up a new issue for this intermittent behaviour.

![Uploading git#883.gif…]()

**Comment by vikasrohit** [comment] 2020-11-12 06:56
@drasticdpk can we mark it as pass now?

**Comment by drasticdpk** [comment] 2020-11-12 10:10
@vikasrohit   sure please.

**Comment by vikasrohit** [comment] 2020-11-12 12:31
Thanks @drasticdpk. @lakshmiathreya  Can we please get it verified on prod as well now?

**Comment by sandhiyakavi** [comment] 2020-11-20 10:44
Verified on Prod.Working as expected.

[issue#883.zip](https://github.com/topcoder-platform/work-manager/files/5572965/issue.883.zip)

**Closed by sandhiyakavi** 2020-11-20 10:44 UTC
Labels: Functional, P0, QA Pass in Dev, QA Pass in Prod, question

**Comment by lakshmiathreya** [comment] 2020-12-10 07:12
@vikasrohit this is one Issue which has the " User [USER] already has resource with roleId: [ROLE-ID] " message showing up - should we reopen it. cc @drasticdpk
