### ISSUE TITLE
Unable to save properly after editing the spec second time

### ISSUE THREAD

**Issue by 0xf17** [topcoder-platform/work-manager#1039] opened 2021-01-14 05:27 UTC
### Expected behavior
WM should save the new updates.

### Actual behavior
WM throws error while saving the edited specification.

### Steps to reproduce the problem
- Create new work > Challenge
- Add public spec and rest of the details
- Save as draft
- Go back to home view and navigate to the same challenge
- Edit the public spec
- Save as draft again
- WM shows the following error but looks like it is actually saving the edit as I'm able to see the new changes in the draft preview.

### Screenshot/screencast
<img width="1118" alt="Screenshot 2021-01-14 at 10 55 26 AM" src="https://user-images.githubusercontent.com/2363826/104548540-07ec4400-5657-11eb-8edd-b6e7d1342f40.png">

--

#### Environment
- OS: macOS BigSur - Version 11.1
- Browser (w/version): Safari - Version 14.0.2 (16610.3.7.1.9)
- User role (client, copilot or manager): Copilot
- Account used: grv.ashu

**Comment by maxceem** [comment] 2021-02-19 10:16
This seems to be a duplicate of the already fixed issue https://github.com/topcoder-platform/work-manager/issues/1066.

@lakshmiathreya do you think we can close it? Or should we QA this first?

**Comment by vikasrohit** [comment] 2021-02-19 11:51
Yes, it is exactly that issue but it was reported earlier then we found how to reproduce it, so thanks @0xf17 for early feedback.

**Closed by vikasrohit** 2021-02-19 11:51 UTC
Labels: Duplicate, Release Due Date: 3/12
