### ISSUE TITLE
Wrong position of validating message for Public Specification.

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/work-manager#959] opened 2020-12-10 11:20 UTC
**Steps**
 1. Save draft challenge without filling required fields. 

**Reference**

![image](https://user-images.githubusercontent.com/25297859/101765499-7d6d6d80-3b09-11eb-9047-fdec4dda06c7.png)

**Comment by drasticdpk** [comment] 2020-12-10 11:20
cc @lakshmiathreya

**Comment by vikasrohit** [comment] 2020-12-10 11:25
Duplicate of #958

**Closed by vikasrohit** 2020-12-10 11:25 UTC
Labels: P1
