### ISSUE TITLE
[$200] Work Manager: Add view of registrants to WM

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#1166] opened 2021-06-10 05:10 UTC
When viewing a challenge in WM, I should be able to see a simple list of the registrants.  Mimic the challenge page design:
![image](https://user-images.githubusercontent.com/2417632/121468361-4acd0080-c9d8-11eb-93e1-b01e29ea12a7.png)

**Move current content in 'View Details' under first tab 'Details'**

**Comment by phead198708** [comment] 2021-06-15 15:42
for actual registrations we have to use https://github.com/topcoder-platform/resources-api/blob/develop/docs/swagger.yaml#L54 endpoint with roleId query param being the role id of the Submitter

**Comment by narekcat** [comment] 2021-06-15 16:06
Hi @maxceem . Can I work on this issue ?

**Comment by maxceem** [comment] 2021-06-15 16:08
Hi @narekcat I'm not a copilot of this task.

@phead198708 it looks like TCX is configured to use my user for repository.

**Comment by phead198708** [comment] 2021-06-15 16:15
Hi, @maxceem  Im new to this project. So I need to use 'Open for Pickup' label ?

**Comment by narekcat** [comment] 2021-06-15 16:23
@maxceem Ok. The bug bush challenge is started for this issue, but in my opinion 12 hours is less for this issue. @phead198708 Can we work on this issue 24 hour ?

**Comment by narekcat** [comment] 2021-06-15 16:27
@bug-bash-helper assign

**Comment by narekcat** [comment] 2021-06-15 16:28
@bug-bash-helper assign

**Comment by narekcat** [comment] 2021-06-15 16:30
@bug-bash-helper assign

**Comment by phead198708** [comment] 2021-06-15 16:37
> @bug-bash-helper assign

sorry @narekcat  pls wait a minute. Let me correct the ticket firstly.

**Comment by narekcat** [comment] 2021-06-15 16:37
@phead198708 Ok, no problem.

**Comment by phead198708** [comment] 2021-06-15 16:42
Hi, @narekcat  it is open for pick now.

**Comment by narekcat** [comment] 2021-06-15 16:43
@bug-bash-helper assign

**Comment by narekcat** [comment] 2021-06-15 16:45
@bug-bash-helper assign

**Comment by narekcat** [comment] 2021-06-15 16:46
Hi, @phead198708 I have tried, but it still isn't working.

**Comment by maxceem** [comment] 2021-06-15 16:46
@narekcat please try now

**Comment by phead198708** [comment] 2021-06-15 16:46
@narekcat  could you try this command ?

**Comment by narekcat** [comment] 2021-06-15 16:46
@bug-bash-helper assign

**Comment by narekcat** [comment] 2021-06-15 16:48
> @narekcat could you try this command ?

Yes. I have tried again.

**Comment by phead198708** [comment] 2021-06-15 16:55
Challenge https://www.topcoder.com/challenges/83f67a65-e65a-4755-845d-31cbee073959 Narekvar90 has been unassigned.<br/><br/>```This is an automated message for phead via Topcoder X```

**Comment by phead198708** [comment] 2021-06-15 16:55
Narekvar90 has been unassigned because this ticket doesn't have the tcx_OpenForPickup label.<br/><br/>```This is an automated message for phead via Topcoder X```

**Comment by phead198708** [comment] 2021-06-15 16:56
Challenge https://www.topcoder.com/challenges/83f67a65-e65a-4755-845d-31cbee073959 has been assigned to Narekvar90.<br/><br/>```This is an automated message for phead via Topcoder X```

**Comment by phead198708** [comment] 2021-06-15 16:57
Hi, @narekcat  assigned, pls work on it.

**Comment by narekcat** [comment] 2021-06-15 16:58
Hi, @phead198708 . Ok, thank you.

**Comment by phead198708** [comment] 2021-06-15 17:06
Challenge https://www.topcoder.com/challenges/23584ff5-ad15-411f-bccc-60b358676a52 has been created for this ticket.<br/><br/>```This is an automated message for phead via Topcoder X```

**Comment by phead198708** [comment] 2021-06-15 17:06
Challenge https://www.topcoder.com/challenges/23584ff5-ad15-411f-bccc-60b358676a52 has been assigned to Narekvar90.<br/><br/>```This is an automated message for phead via Topcoder X```

**Comment by phead198708** [comment] 2021-06-15 17:07
Challenge https://www.topcoder.com/challenges/edb8ba3e-7a2d-40ae-b831-b6cc49ef2a51 has been created for this ticket.<br/><br/>```This is an automated message for phead via Topcoder X```

**Comment by phead198708** [comment] 2021-06-15 17:07
Challenge https://www.topcoder.com/challenges/edb8ba3e-7a2d-40ae-b831-b6cc49ef2a51 has been assigned to Narekvar90.<br/><br/>```This is an automated message for phead via Topcoder X```

**Comment by vikasrohit** [comment] 2021-06-15 17:09
@bug-bash-helper assign

**Comment by phead198708** [comment] 2021-06-15 17:09
@vikasrohit, please sign-up with Topcoder X tool<br/><br/>```This is an automated message for phead via Topcoder X```

**Comment by phead198708** [comment] 2021-06-15 17:09
Challenge https://www.topcoder.com/challenges/edb8ba3e-7a2d-40ae-b831-b6cc49ef2a51 Narekvar90 has been unassigned.<br/><br/>```This is an automated message for phead via Topcoder X```

**Comment by phead198708** [comment] 2021-06-15 17:09
@vikasrohit, please sign-up with Topcoder X tool<br/><br/>```This is an automated message for phead via Topcoder X```

**Comment by narekcat** [comment] 2021-06-15 17:10
Hi, @vikasrohit. I am already working on this issue and this issue assigned to me.

**Comment by vikasrohit** [comment] 2021-06-15 17:11
Yep, @narekcat you are the assignee of the issue. I am from topcoder and testing the bot to fix it. It seems it is working now.

**Comment by narekcat** [comment] 2021-06-15 17:11
@vikasrohit Ok.

**Comment by phead198708** [comment] 2021-06-15 17:11
Challenge https://www.topcoder.com/challenges/edb8ba3e-7a2d-40ae-b831-b6cc49ef2a51 has been assigned to Narekvar90.<br/><br/>```This is an automated message for phead via Topcoder X```

**Comment by nursoltan-s** [comment] 2021-06-16 02:32
@bug-bash-helper assign

**Comment by nursoltan-s** [comment] 2021-06-16 02:33
@bug-bash-helper unassign

**Comment by phead198708** [comment] 2021-06-16 04:36
Hi, @narekcat 

Are you still working on this ticket ?

**Comment by narekcat** [comment] 2021-06-16 06:15
Hi, @phead198708 . I am still working on this issue. This issue is big then other, and I think I have 11 hours to complete it.

**Comment by phead198708** [comment] 2021-06-16 08:10
Hi, @narekcat 

Pls finish this asap. You have worked on it over 12hr. thx

**Comment by narekcat** [comment] 2021-06-16 08:13
@phead198708 Ok, I'll finish it in next 8 hours, but in bug bush rules it says that I can work on it 24 hours (https://github.com/topcoder-platform/work-manager/issues/1177). Am I right ?

**Comment by phead198708** [comment] 2021-06-16 08:53
OK，This is an auto-generated one.  I explain in challenge spec, developer can hold one ticket 12hr.

Never mind, keep going on, and update the status once you get this ticket done.

**Comment by narekcat** [comment] 2021-06-16 08:57
@phead198708 Ok, thank you.

**Comment by narekcat** [comment] 2021-06-16 10:49
@bug-bash-helper https://github.com/topcoder-platform/work-manager/pull/1181 is ready for review

**Comment by narekcat** [comment] 2021-06-16 10:50
@phead198708 I have fixed this issue. If there is suggestion about styles, I'll fix them too.

**Comment by phead198708** [comment] 2021-06-16 18:15
Hi, @narekcat 

There are many things missing.

1.  Create two tabs in challenge details page, one is 'Details', one is 'Registrants (total registrants)', the tab style you can refer to challenge list page. http://localhost:3000/projects/17249/challenges
2. Move current content under 'Details' tab.
3. List all Registrants under 'Registrants' tab. Pls notice the color of the rating and user name, the sort function in the table header, and the submitted date column. Checking the above image carefully, also you can check any open challenge: https://www.topcoder.com/challenges/e06e6045-96bb-414f-b34c-45961238a6be?tab=registrants

Pls finish it in next 6hr. We already spent many time on this ticket.

**Comment by narekcat** [comment] 2021-06-16 18:25
Hi @phead198708 . It is late in my time zone, I need to have a rest. If it pissible I'll finish this issue in next 16 hours. Is it ok ?

**Comment by narekcat** [comment] 2021-06-17 07:21
Hi @phead198708 . I had misunderstood issue requirement, I thought that it is easier, but now I understand this issue is harder then I thought. I need more time to complete. Also I think the prize is less for this issue. If it is ok, please replay. Can I continue to work on it ? Can you rise the prize ?

**Comment by phead198708** [comment] 2021-06-17 11:08
sorry, it has been opened over 24hr. I have to reopen this ticket.

**Comment by phead198708** [comment] 2021-06-17 11:08
Challenge https://www.topcoder.com/challenges/edb8ba3e-7a2d-40ae-b831-b6cc49ef2a51 Narekvar90 has been unassigned.<br/><br/>```This is an automated message for phead via Topcoder X```

**Comment by yoution** [comment] 2021-06-17 11:55
@phead198708  please assign to me

**Comment by phead198708** [comment] 2021-06-17 12:00
Challenge https://www.topcoder.com/challenges/edb8ba3e-7a2d-40ae-b831-b6cc49ef2a51 has been assigned to yoution.<br/><br/>```This is an automated message for phead via Topcoder X```

**Comment by yoution** [comment] 2021-06-18 02:51
@bug-bash-helper https://github.com/topcoder-platform/work-manager/pull/1185 is ready for review

**Comment by phead198708** [comment] 2021-06-18 04:21
cool, nice fix.

**Comment by yoution** [comment] 2021-06-20 11:55
@vikasrohit  please review this one https://github.com/topcoder-platform/work-manager/pull/1189

**Comment by vikasrohit** [comment] 2021-06-20 12:19
Thanks @yoution for the new PR. I think the changes are already verified by @phead198708 , I just needed it in correct branch so that it don't go to the production unintentionally.

**Comment by coderhacker** [comment] 2021-06-25 10:07
@vikasrohit I am unable to verify this issue due to this regression https://github.com/topcoder-platform/work-manager/issues/1198

**Comment by vikasrohit** [comment] 2021-06-28 05:08
@coderhacker this can be verified for existing challenges as we did with #1169

**Comment by coderhacker** [comment] 2021-06-28 12:13
This is passed on to 
production 

https://user-images.githubusercontent.com/62358241/123634547-37bf8a80-d838-11eb-914b-60b3b8278053.mp4

**Comment by phead198708** [comment] 2021-06-28 12:13
Payment task has been updated: https://www.topcoder.com/challenges/edb8ba3e-7a2d-40ae-b831-b6cc49ef2a51
*Payments Complete*
Winner: yoution
Copilot: phead
Challenge `edb8ba3e-7a2d-40ae-b831-b6cc49ef2a51` has been paid and closed.<br/><br/>```This is an automated message for phead via Topcoder X```

**Closed by coderhacker** 2021-06-28 12:13 UTC
Labels: CF, Dev Environment, Feedback, P2, QA Pass in Prod, Ready for QA, tcx_Assigned, tcx_FixAccepted

**Comment by yoution** [comment] 2021-06-29 15:08
@vikasrohit  I can not receive the payment, can you check it?

**Comment by vikasrohit** [comment] 2021-06-30 08:41
@phead198708 is working to release the payments.
